#ifndef OBD2MODES_H
#define OBD2MODES_H

enum{
	SHOW_CURRENT_DATA											= 0x01,
	SHOW_FREEZE_FRAME_DATA								= 0x02,
	SHOW_STORED_DIAGNOSTIC_TROUBLE_CODES	= 0x03,
	CLEAR_DIAGNOSTIC_TROUBLE_CODES				= 0x04,
	TEST_RESULTS_NON_CAN									= 0x05,
	TEST_RESULTS_CAN											= 0x06,
	SHOW_PENDING_DIAGNOSTIC_TROUBLE_CODES	= 0x07,
	CONTROL_OPERATION_OF_ONBOARD_SYSTEM		= 0x08,
	REQUEST_VEHICLE_INFORMATION						= 0x09,
	PERMANENT_DIAGNOSTIC_TROUBLE_CODES		= 0x0A,
  MODE_RESPONSE_DELTA                   = 0x40
};

#endif
